// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ArtifactoryGroupInitParameters struct {

	// Any users added to this group will automatically be assigned with admin privileges in the system.
	AdminPrivileges *bool `json:"adminPrivileges,omitempty" tf:"admin_privileges,omitempty"`

	// When this parameter is set, any new users defined in the system are automatically assigned to this group.
	AutoJoin *bool `json:"autoJoin,omitempty" tf:"auto_join,omitempty"`

	// A description for the group.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// When this is set to `true`, an empty or missing usernames array will detach all users from the group.
	DetachAllUsers *bool `json:"detachAllUsers,omitempty" tf:"detach_all_users,omitempty"`

	// New external group ID used to configure the corresponding group in Azure AD.
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// Name of the group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// When this override is set, User in the group can set Xray security and compliance policies. Default value is `false`.
	PolicyManager *bool `json:"policyManager,omitempty" tf:"policy_manager,omitempty"`

	// The realm for the group.
	Realm *string `json:"realm,omitempty" tf:"realm,omitempty"`

	// The realm attributes for the group.
	RealmAttributes *string `json:"realmAttributes,omitempty" tf:"realm_attributes,omitempty"`

	// When this override is set, User in the group can manage Xray Reports on any resource type. Default value is `false`.
	ReportsManager *bool `json:"reportsManager,omitempty" tf:"reports_manager,omitempty"`

	// List of users assigned to the group.
	// +listType=set
	UsersNames []*string `json:"usersNames,omitempty" tf:"users_names,omitempty"`

	// When this override is set, User in the group can manage Xray Watches on any resource type. Default value is `false`.
	WatchManager *bool `json:"watchManager,omitempty" tf:"watch_manager,omitempty"`
}

type ArtifactoryGroupObservation struct {

	// Any users added to this group will automatically be assigned with admin privileges in the system.
	AdminPrivileges *bool `json:"adminPrivileges,omitempty" tf:"admin_privileges,omitempty"`

	// When this parameter is set, any new users defined in the system are automatically assigned to this group.
	AutoJoin *bool `json:"autoJoin,omitempty" tf:"auto_join,omitempty"`

	// A description for the group.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// When this is set to `true`, an empty or missing usernames array will detach all users from the group.
	DetachAllUsers *bool `json:"detachAllUsers,omitempty" tf:"detach_all_users,omitempty"`

	// New external group ID used to configure the corresponding group in Azure AD.
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// When this override is set, User in the group can set Xray security and compliance policies. Default value is `false`.
	PolicyManager *bool `json:"policyManager,omitempty" tf:"policy_manager,omitempty"`

	// The realm for the group.
	Realm *string `json:"realm,omitempty" tf:"realm,omitempty"`

	// The realm attributes for the group.
	RealmAttributes *string `json:"realmAttributes,omitempty" tf:"realm_attributes,omitempty"`

	// When this override is set, User in the group can manage Xray Reports on any resource type. Default value is `false`.
	ReportsManager *bool `json:"reportsManager,omitempty" tf:"reports_manager,omitempty"`

	// List of users assigned to the group.
	// +listType=set
	UsersNames []*string `json:"usersNames,omitempty" tf:"users_names,omitempty"`

	// When this override is set, User in the group can manage Xray Watches on any resource type. Default value is `false`.
	WatchManager *bool `json:"watchManager,omitempty" tf:"watch_manager,omitempty"`
}

type ArtifactoryGroupParameters struct {

	// Any users added to this group will automatically be assigned with admin privileges in the system.
	// +kubebuilder:validation:Optional
	AdminPrivileges *bool `json:"adminPrivileges,omitempty" tf:"admin_privileges,omitempty"`

	// When this parameter is set, any new users defined in the system are automatically assigned to this group.
	// +kubebuilder:validation:Optional
	AutoJoin *bool `json:"autoJoin,omitempty" tf:"auto_join,omitempty"`

	// A description for the group.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// When this is set to `true`, an empty or missing usernames array will detach all users from the group.
	// +kubebuilder:validation:Optional
	DetachAllUsers *bool `json:"detachAllUsers,omitempty" tf:"detach_all_users,omitempty"`

	// New external group ID used to configure the corresponding group in Azure AD.
	// +kubebuilder:validation:Optional
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// Name of the group.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// When this override is set, User in the group can set Xray security and compliance policies. Default value is `false`.
	// +kubebuilder:validation:Optional
	PolicyManager *bool `json:"policyManager,omitempty" tf:"policy_manager,omitempty"`

	// The realm for the group.
	// +kubebuilder:validation:Optional
	Realm *string `json:"realm,omitempty" tf:"realm,omitempty"`

	// The realm attributes for the group.
	// +kubebuilder:validation:Optional
	RealmAttributes *string `json:"realmAttributes,omitempty" tf:"realm_attributes,omitempty"`

	// When this override is set, User in the group can manage Xray Reports on any resource type. Default value is `false`.
	// +kubebuilder:validation:Optional
	ReportsManager *bool `json:"reportsManager,omitempty" tf:"reports_manager,omitempty"`

	// List of users assigned to the group.
	// +kubebuilder:validation:Optional
	// +listType=set
	UsersNames []*string `json:"usersNames,omitempty" tf:"users_names,omitempty"`

	// When this override is set, User in the group can manage Xray Watches on any resource type. Default value is `false`.
	// +kubebuilder:validation:Optional
	WatchManager *bool `json:"watchManager,omitempty" tf:"watch_manager,omitempty"`
}

// ArtifactoryGroupSpec defines the desired state of ArtifactoryGroup
type ArtifactoryGroupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ArtifactoryGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ArtifactoryGroupInitParameters `json:"initProvider,omitempty"`
}

// ArtifactoryGroupStatus defines the observed state of ArtifactoryGroup.
type ArtifactoryGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ArtifactoryGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ArtifactoryGroup is the Schema for the ArtifactoryGroups API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,jfrogartifactory}
type ArtifactoryGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ArtifactoryGroupSpec   `json:"spec"`
	Status ArtifactoryGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ArtifactoryGroupList contains a list of ArtifactoryGroups
type ArtifactoryGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ArtifactoryGroup `json:"items"`
}

// Repository type metadata.
var (
	ArtifactoryGroup_Kind             = "ArtifactoryGroup"
	ArtifactoryGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ArtifactoryGroup_Kind}.String()
	ArtifactoryGroup_KindAPIVersion   = ArtifactoryGroup_Kind + "." + CRDGroupVersion.String()
	ArtifactoryGroup_GroupVersionKind = CRDGroupVersion.WithKind(ArtifactoryGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&ArtifactoryGroup{}, &ArtifactoryGroupList{})
}
