apiVersion: repository.upbound.io/v1alpha1
kind: RemoteMavenRepository
metadata:
  name: remotemavenrepository
  annotations:
    crossplane.io/external-name: "remotemavenrepository"
spec:
  forProvider:
    description: "new remote maven repository"
    url: <url>
    username: <uname>
    passwordSecretRef:
      key: passwords
      name: example-creds-read
      namespace: crossplane-system
    contentSynchronisation:
      - enabled:  true
        propertiesEnabled: true
        sourceOriginAbsenceDetection:  true
        statisticsEnabled : true
  providerConfigRef:
    name: my-artifactory-providerconfig-read