apiVersion: jfrogartifactory.upbound.io/v1alpha1
kind: RemoteNpmRepository
metadata:
  name: remotenpmrepository
  annotations:
    crossplane.io/external-name: "remotenpmrepository"
spec:
  forProvider:
    description: "new remote npm repository"
    url: <url>
    username: <uname>
    passwordSecretRef:
      key: password
      name: secret-read
      namespace: crossplane-system
    contentSynchronisation:
      - enabled:  true
        propertiesEnabled: true
        sourceOriginAbsenceDetection:  true
        statisticsEnabled : true
  providerConfigRef:
    name: my-artifactory-providerconfig-read