apiVersion: repository.upbound.io/v1alpha1
kind: RemoteMavenRepository
metadata:
  name: remotemavenrepository
  annotations:
    crossplane.io/external-name: "remotemavenrepository"
spec:
  forProvider:
    description: "new remote maven repository"
    url: https://amer-write.binrepo.guidewire.net/artifactory/api/maven/localmavenrepository/
    username: sys-re-binrepo
    passwordSecretRef:
      key: passwords
      name: example-creds-read
      namespace: crossplane-system
    contentSynchronisation:
      - enabled:  true
        propertiesEnabled: true
        sourceOriginAbsenceDetection:  true
        statisticsEnabled : true
  providerConfigRef:
    name: my-artifactory-providerconfig-read