apiVersion: jfrogartifactory.upbound.io/v1alpha1
kind: VirtualMavenRepository
metadata:
  name: virtualmavenrepository
  annotations:
    crossplane.io/external-name: "virtualmavenrepository"
spec:
  forProvider:
    description: "new virtual maven repository"
    repoLayoutRef: "maven-2-default"
    repositories:
    - alpine-mvn-release-local
    - remotemavenrepository
  providerConfigRef:
    name: my-artifactory-providerconfig-read
