apiVersion: batch/v1
kind: Job
metadata:
  name: create-credentials
spec:
  template:
    spec:
      containers:
      - name: main
        image: alpine:latest
        command:
          - /bin/sh
          - -c
          - |
            #!/bin/sh
            set -e
            echo "Updating package index..."
            apk update
            echo "Installing kubectl, curl, and jq..."
            apk add --no-cache curl jq
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            mv kubectl /usr/local/bin/

            ### CREATE CREDENTIALS ###
            mkdir /work
            echo "Calling artifactory API to create credentials..."
            curl -v -X POST -u admin:password http://artifactory-artifactory-nginx.jfrog:80/access/api/v1/tokens > /work/curl.out
            jq '{access_token: .access_token, url: "http://localhost:8888"}' /work/curl.out > /work/creds.json
            kubectl delete secret artifactory-credentials || true
            kubectl create secret generic artifactory-credentials --from-file=/work/creds.json
      restartPolicy: Never
      serviceAccountName: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: create-credentials
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-credentials
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: create-credentials
  apiGroup: rbac.authorization.k8s.io