apiVersion: jfrogartifactory.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: my-artifactory-providerconfig-read
spec:
  credentials:
    source: Secret
    secretRef:
      name: artifactory-credentials-read
      namespace: default
      key: creds-read.json
